// Supported app languages
enum AppLanguage { italian, swahili }

// Italian question data class with translation and audio fields
class Question {
  final int id;
  final String questionText;
  final String questionTranslation;
  final List<String> options;
  final List<String> optionTranslations;
  final int correctAnswerIndex;
  final String questionType;
  final String questionTypeTranslation;
  final String pronunciation;
  final String explanation;
  final String explanationTranslation;
  // Field for Text-to-Speech engine
  final String audioPhrase;

  const Question({
    required this.id,
    required this.questionText,
    this.questionTranslation = "",
    required this.options,
    this.optionTranslations = const [],
    required this.correctAnswerIndex,
    this.questionType = "",
    this.questionTypeTranslation = "",
    this.pronunciation = "",
    this.explanation = "",
    this.explanationTranslation = "",
    this.audioPhrase = "",
  });
}

class QuestionRepository {
  // Private constructor for singleton pattern
  QuestionRepository._();

  // Static instance
  static final QuestionRepository _instance = QuestionRepository._();

  // Factory constructor returns the same instance
  factory QuestionRepository() => _instance;

  List<Question> getItalianQuestions() {
    return [
      // --- University & Enrollment ---
      const Question(
        id: 1,
        questionType: "University - Enrollment",
        questionTypeTranslation: "University - Enrollment",
        questionText: "How do you say 'I am a computer science student'?",
        questionTranslation: "How do you say 'I am a computer science student'?",
        options: ["Sono uno studente di informatica", "Studio legge", "Cerco lavoro", "Vado all'università"],
        optionTranslations: ["I am a computer science student", "I study law", "I am looking for work", "I go to university"],
        correctAnswerIndex: 0,
        pronunciation: "SO-no U-no stu-DEN-te di in-for-MA-ti-ca",
        explanation: "Use this phrase to introduce your field of study.",
        explanationTranslation: "Use this phrase to introduce your field of study.",
        audioPhrase: "Sono uno studente di informatica",
      ),
      const Question(
        id: 2,
        questionType: "University - Office",
        questionTypeTranslation: "University - Office",
        questionText: "What is the 'Segreteria Studenti'?",
        questionTranslation: "What is the 'Segreteria Studenti'?",
        options: ["Student Cafeteria", "Student Office/Registrar", "Library", "Gym"],
        optionTranslations: ["Mensa", "Segreteria Studenti", "Biblioteca", "Palestra"],
        correctAnswerIndex: 1,
        pronunciation: "se-gre-te-RI-a stu-DEN-ti",
        explanation: "The Segreteria is where you handle administrative tasks like enrollment.",
        explanationTranslation: "The Segreteria is where you handle administrative tasks like enrollment.",
        audioPhrase: "la segreteria studenti",
      ),
      const Question(
        id: 3,
        questionType: "University - ID",
        questionTypeTranslation: "University - ID",
        questionText: "What does 'numero di matricola' mean?",
        questionTranslation: "What does 'numero di matricola' mean?",
        options: ["Phone number", "Student ID number", "Course number", "Room number"],
        optionTranslations: ["Numero di telefono", "Numero di matricola", "Numero del corso", "Numero della stanza"],
        correctAnswerIndex: 1,
        pronunciation: "NU-me-ro di ma-TRI-co-la",
        explanation: "This is your unique identification number at the university.",
        explanationTranslation: "This is your unique identification number at the university.",
        audioPhrase: "il numero di matricola",
      ),
      const Question(
        id: 4,
        questionType: "University - Classes",
        questionTypeTranslation: "University - Classes",
        questionText: "How do you ask 'When do classes start?'",
        questionTranslation: "How do you ask 'When do classes start?'",
        options: ["Quando finiscono le lezioni?", "Quando iniziano le lezioni?", "Dove sono le lezioni?", "Chi insegna?"],
        optionTranslations: ["When do classes end?", "When do classes start?", "Where are the classes?", "Who teaches?"],
        correctAnswerIndex: 1,
        pronunciation: "KWAN-do i-NI-zia-no le le-ZIO-ni",
        explanation: "Useful for planning your academic calendar.",
        explanationTranslation: "Useful for planning your academic calendar.",
        audioPhrase: "Quando iniziano le lezioni?",
      ),

      // --- Bureaucracy & Visa ---
      const Question(
        id: 5,
        questionType: "Bureaucracy - Permit",
        questionTypeTranslation: "Bureaucracy - Permit",
        questionText: "What is the 'Permesso di soggiorno'?",
        questionTranslation: "What is the 'Permesso di soggiorno'?",
        options: ["Driving license", "Residence permit", "Library card", "Travel visa"],
        optionTranslations: ["Patente", "Permesso di soggiorno", "Tessera della biblioteca", "Visto turistico"],
        correctAnswerIndex: 1,
        pronunciation: "per-MES-so di sog-GIOR-no",
        explanation: "The essential document for staying in Italy longer than 3 months.",
        explanationTranslation: "The essential document for staying in Italy longer than 3 months.",
        audioPhrase: "il permesso di soggiorno",
      ),
      const Question(
        id: 6,
        questionType: "Bureaucracy - Tax Code",
        questionTypeTranslation: "Bureaucracy - Tax Code",
        questionText: "What is the 'Codice Fiscale'?",
        questionTranslation: "What is the 'Codice Fiscale'?",
        options: ["Tax code", "Zip code", "Student code", "Bank code"],
        optionTranslations: ["Codice Fiscale", "CAP", "Codice studente", "Codice bancario"],
        correctAnswerIndex: 0,
        pronunciation: "CO-di-ce fis-CA-le",
        explanation: "You need this alphanumeric code for everything from renting a flat to opening a bank account.",
        explanationTranslation: "You need this alphanumeric code for everything from renting a flat to opening a bank account.",
        audioPhrase: "il codice fiscale",
      ),
      const Question(
        id: 7,
        questionType: "Bureaucracy - Appointment",
        questionTypeTranslation: "Bureaucracy - Appointment",
        questionText: "How do you say 'I need to make an appointment'?",
        questionTranslation: "How do you say 'I need to make an appointment'?",
        options: ["Devo fare una domanda", "Devo prendere un appuntamento", "Voglio andare via", "Cerco un ufficio"],
        optionTranslations: ["I need to apply", "I need to make an appointment", "I want to leave", "I'm looking for an office"],
        correctAnswerIndex: 1,
        pronunciation: "DE-vo PREN-de-re un ap-pun-ta-MEN-to",
        explanation: "Essential for visiting the Questura or other offices.",
        explanationTranslation: "Essential for visiting the Questura or other offices.",
        audioPhrase: "Devo prendere un appuntamento",
      ),

      // --- Job Search & Work ---
      const Question(
        id: 8,
        questionType: "Work - Job Search",
        questionTypeTranslation: "Work - Job Search",
        questionText: "How do you say 'I am looking for a part-time job'?",
        questionTranslation: "How do you say 'I am looking for a part-time job'?",
        options: ["Cerco un lavoro part-time", "Cerco un lavoro a tempo pieno", "Non voglio lavorare", "Studio solo"],
        optionTranslations: ["I am looking for a part-time job", "I am looking for a full-time job", "I don't want to work", "I only study"],
        correctAnswerIndex: 0,
        pronunciation: "CER-co un la-VO-ro part-time",
        explanation: "Common for students balancing work and study.",
        explanationTranslation: "Common for students balancing work and study.",
        audioPhrase: "Cerco un lavoro part-time",
      ),
      const Question(
        id: 9,
        questionType: "Work - Resume",
        questionTypeTranslation: "Work - Resume",
        questionText: "What is a 'Curriculum Vitae'?",
        questionTranslation: "What is a 'Curriculum Vitae'?",
        options: ["Job contract", "Resume/CV", "Cover letter", "Interview"],
        optionTranslations: ["Contratto", "Curriculum Vitae", "Lettera di presentazione", "Colloquio"],
        correctAnswerIndex: 1,
        pronunciation: "cur-RI-cu-lum VI-tae",
        explanation: "The document outlining your skills and experience.",
        explanationTranslation: "The document outlining your skills and experience.",
        audioPhrase: "il curriculum vitae",
      ),
      const Question(
        id: 10,
        questionType: "Work - Interview",
        questionTypeTranslation: "Work - Interview",
        questionText: "What does 'il colloquio di lavoro' mean?",
        questionTranslation: "What does 'il colloquio di lavoro' mean?",
        options: ["Job offer", "Job interview", "Dismissal", "Promotion"],
        optionTranslations: ["Offerta di lavoro", "Colloquio di lavoro", "Licenziamento", "Promozione"],
        correctAnswerIndex: 1,
        pronunciation: "il col-LO-quio di la-VO-ro",
        explanation: "The meeting where you are evaluated for a job.",
        explanationTranslation: "The meeting where you are evaluated for a job.",
        audioPhrase: "il colloquio di lavoro",
      ),
      const Question(
        id: 11,
        questionType: "Work - Internship",
        questionTypeTranslation: "Work - Internship",
        questionText: "What is a 'tirocinio' or 'stage'?",
        questionTranslation: "What is a 'tirocinio' or 'stage'?",
        options: ["Internship", "Full-time job", "Holiday", "Exam"],
        optionTranslations: ["Tirocinio", "Lavoro a tempo pieno", "Vacanza", "Esame"],
        correctAnswerIndex: 0,
        pronunciation: "ti-ro-CI-nio",
        explanation: "Work experience often required by universities.",
        explanationTranslation: "Work experience often required by universities.",
        audioPhrase: "il tirocinio",
      ),

      // --- Housing & Daily Life ---
      const Question(
        id: 12,
        questionType: "Housing - Room",
        questionTypeTranslation: "Housing - Room",
        questionText: "How do you say 'I am looking for a single room'?",
        questionTranslation: "How do you say 'I am looking for a single room'?",
        options: ["Cerco una camera singola", "Cerco una camera doppia", "Cerco un appartamento", "Cerco un hotel"],
        optionTranslations: ["I am looking for a single room", "I am looking for a double room", "I am looking for an apartment", "I am looking for a hotel"],
        correctAnswerIndex: 0,
        pronunciation: "CER-co U-na CA-me-ra SIN-go-la",
        explanation: "Useful when searching for student accommodation.",
        explanationTranslation: "Useful when searching for student accommodation.",
        audioPhrase: "Cerco una camera singola",
      ),
      const Question(
        id: 13,
        questionType: "Housing - Rent",
        questionTypeTranslation: "Housing - Rent",
        questionText: "What does 'l\u2019affitto' mean?",
        questionTranslation: "What does 'l\u2019affitto' mean?",
        options: ["The sale", "The rent", "The bills", "The deposit"],
        optionTranslations: ["La vendita", "L'affitto", "Le bollette", "La caparra"],
        correctAnswerIndex: 1,
        pronunciation: "laf-FIT-to",
        explanation: "The monthly payment for your accommodation.",
        explanationTranslation: "The monthly payment for your accommodation.",
        audioPhrase: "l'affitto",
      ),
      const Question(
        id: 14,
        questionType: "Life - Bank",
        questionTypeTranslation: "Life - Bank",
        questionText: "How do you say 'I want to open a bank account'?",
        questionTranslation: "How do you say 'I want to open a bank account'?",
        options: ["Voglio chiudere il conto", "Voglio aprire un conto bancario", "Ho bisogno di soldi", "Dov'è la banca?"],
        optionTranslations: ["I want to close the account", "I want to open a bank account", "I need money", "Where is the bank?"],
        correctAnswerIndex: 1,
        pronunciation: "VO-glio a-PRI-re un CON-to ban-CA-rio",
        explanation: "Necessary for receiving your scholarship or salary.",
        explanationTranslation: "Necessary for receiving your scholarship or salary.",
        audioPhrase: "Voglio aprire un conto bancario",
      ),
      const Question(
        id: 15,
        questionType: "Life - SIM Card",
        questionTypeTranslation: "Life - SIM Card",
        questionText: "How do you ask for a SIM card?",
        questionTranslation: "How do you ask for a SIM card?",
        options: ["Vorrei una scheda SIM", "Vorrei un telefono", "Vorrei internet", "Vorrei chiamare"],
        optionTranslations: ["I would like a SIM card", "I would like a phone", "I would like internet", "I would like to call"],
        correctAnswerIndex: 0,
        pronunciation: "vor-REI U-na SKE-da SIM",
        explanation: "Getting a local number is one of the first things to do.",
        explanationTranslation: "Getting a local number is one of the first things to do.",
        audioPhrase: "Vorrei una scheda SIM",
      ),

      // --- Social & Networking ---
      const Question(
        id: 16,
        questionType: "Social - Meeting",
        questionTypeTranslation: "Social - Meeting",
        questionText: "How do you ask 'Are there events for international students?'",
        questionTranslation: "How do you ask 'Are there events for international students?'",
        options: ["Ci sono eventi per studenti internazionali?", "Dove sono gli studenti?", "Quando è la festa?", "Chi è internazionale?"],
        optionTranslations: ["Are there events for international students?", "Where are the students?", "When is the party?", "Who is international?"],
        correctAnswerIndex: 0,
        pronunciation: "ci SO-no e-VEN-ti per stu-DEN-ti in-ter-na-zio-NA-li",
        explanation: "Good for networking and making friends.",
        explanationTranslation: "Good for networking and making friends.",
        audioPhrase: "Ci sono eventi per studenti internazionali?",
      ),
      const Question(
        id: 17,
        questionType: "Social - Language",
        questionTypeTranslation: "Social - Language",
        questionText: "How do you say 'I don\u2019t speak Italian very well'?",
        questionTranslation: "How do you say 'I don\u2019t speak Italian very well'?",
        options: ["Parlo bene italiano", "Non parlo molto bene l'italiano", "Sono italiano", "Capisco tutto"],
        optionTranslations: ["I speak Italian well", "I don't speak Italian very well", "I am Italian", "I understand everything"],
        correctAnswerIndex: 1,
        pronunciation: "non PAR-lo MOL-to BE-ne li-ta-LIA-no",
        explanation: "A useful phrase to manage expectations when learning.",
        explanationTranslation: "A useful phrase to manage expectations when learning.",
        audioPhrase: "Non parlo molto bene l'italiano",
      ),
      const Question(
        id: 18,
        questionType: "University - Scholarship",
        questionTypeTranslation: "University - Scholarship",
        questionText: "What is a 'Borsa di studio'?",
        questionTranslation: "What is a 'Borsa di studio'?",
        options: ["Study bag", "Scholarship", "Tuition fee", "Exam result"],
        optionTranslations: ["Borsa", "Borsa di studio", "Tassa universitaria", "Risultato esame"],
        correctAnswerIndex: 1,
        pronunciation: "BOR-sa di STU-dio",
        explanation: "Financial aid to help with your studies.",
        explanationTranslation: "Financial aid to help with your studies.",
        audioPhrase: "la borsa di studio",
      ),
      const Question(
        id: 19,
        questionType: "Life - Health",
        questionTypeTranslation: "Life - Health",
        questionText: "What is the 'Tessera Sanitaria'?",
        questionTranslation: "What is the 'Tessera Sanitaria'?",
        options: ["Health insurance card", "Travel card", "Identity card", "Credit card"],
        optionTranslations: ["Tessera sanitaria", "Abbonamento mezzi", "Carta d'identità", "Carta di credito"],
        correctAnswerIndex: 0,
        pronunciation: "TES-se-ra sa-ni-TA-ria",
        explanation: "Your national health service card for accessing doctors.",
        explanationTranslation: "Your national health service card for accessing doctors.",
        audioPhrase: "la tessera sanitaria",
      ),
      const Question(
        id: 20,
        questionType: "Work - Contract",
        questionTypeTranslation: "Work - Contract",
        questionText: "How do you ask 'What type of contract is it?'",
        questionTranslation: "How do you ask 'What type of contract is it?'",
        options: ["Quanto mi paghi?", "Che tipo di contratto è?", "Quando inizio?", "Dove firmo?"],
        optionTranslations: ["How much do you pay me?", "What type of contract is it?", "When do I start?", "Where do I sign?"],
        correctAnswerIndex: 1,
        pronunciation: "ke TI-po di con-TRAT-to è",
        explanation: "Important to know if it's temporary, permanent, or an apprenticeship.",
        explanationTranslation: "Important to know if it's temporary, permanent, or an apprenticeship.",
        audioPhrase: "Che tipo di contratto è?",
      ),
    ];
  }

  // Backward compatibility
  List<Question> getQuestions() {
    return getItalianQuestions();
  }

  List<Question> getSwahiliQuestions() {
    return [
      // --- Greetings & Introductions ---
      const Question(
        id: 101,
        questionType: "Greetings - General",
        questionTypeTranslation: "Salamu - Jumla",
        questionText: "How do you ask 'How are you?' in Swahili?",
        questionTranslation: "Unasemaje 'How are you?' kwa Kiswahili?",
        options: ["Habari yako?", "Jina lako nani?", "Unaishi wapi?", "Asante sana"],
        optionTranslations: ["How are you? (What's your news?)", "What is your name?", "Where do you live?", "Thank you very much"],
        correctAnswerIndex: 0,
        pronunciation: "Ha-BA-ri YA-ko",
        explanation: "Habari yako? literally means 'What is your news?' — the standard everyday greeting.",
        explanationTranslation: "Habari yako? literally means 'What is your news?' — the standard everyday greeting.",
        audioPhrase: "Habari yako?",
      ),
      const Question(
        id: 102,
        questionType: "Greetings - Introduction",
        questionTypeTranslation: "Salamu - Utambulisho",
        questionText: "How do you say 'My name is ...' in Swahili?",
        questionTranslation: "Unasemaje 'Jina langu ni ...' kwa Kiswahili?",
        options: ["Mimi ni mzuri", "Jina langu ni ...", "Ninatoka ...", "Ninaishi ..."],
        optionTranslations: ["I am fine", "My name is ...", "I come from ...", "I live in ..."],
        correctAnswerIndex: 1,
        pronunciation: "JI-na LAN-gu ni",
        explanation: "'Jina langu ni...' is the standard way to introduce yourself by name.",
        explanationTranslation: "'Jina langu ni...' is the standard way to introduce yourself by name.",
        audioPhrase: "Jina langu ni",
      ),
      const Question(
        id: 103,
        questionType: "Greetings - Respectful",
        questionTypeTranslation: "Salamu - Heshima",
        questionText: "What is the respectful greeting said to elders: 'Shikamoo'?",
        questionTranslation: "Ni salamu gani ya heshima kwa wazee: 'Shikamoo'?",
        options: ["Good morning", "I hold your feet (respectful greeting)", "Goodbye", "How are you?"],
        optionTranslations: ["Asubuhi njema", "Shikamoo (salamu ya heshima)", "Kwa heri", "Habari yako?"],
        correctAnswerIndex: 1,
        pronunciation: "Shi-KA-moo",
        explanation: "'Shikamoo' is used to greet elders respectfully; the response is 'Marahaba'.",
        explanationTranslation: "'Shikamoo' is used to greet elders respectfully; the response is 'Marahaba'.",
        audioPhrase: "Shikamoo",
      ),
      const Question(
        id: 104,
        questionType: "Greetings - Farewell",
        questionTypeTranslation: "Salamu - Kuaga",
        questionText: "How do you say 'Goodbye' in Swahili?",
        questionTranslation: "Unasemaje 'Goodbye' kwa Kiswahili?",
        options: ["Karibu", "Asante", "Kwa heri", "Samahani"],
        optionTranslations: ["Welcome / Come in", "Thank you", "Goodbye", "Sorry / Excuse me"],
        correctAnswerIndex: 2,
        pronunciation: "Kwa HE-ri",
        explanation: "'Kwa heri' is used when saying goodbye to one person; 'Kwa herini' for a group.",
        explanationTranslation: "'Kwa heri' is used when saying goodbye to one person; 'Kwa herini' for a group.",
        audioPhrase: "Kwa heri",
      ),

      // --- Shopping & the Market ---
      const Question(
        id: 105,
        questionType: "Shopping - Price",
        questionTypeTranslation: "Ununuzi - Bei",
        questionText: "How do you ask 'How much does it cost?' in Swahili?",
        questionTranslation: "Unaulizaje 'How much does it cost?' kwa Kiswahili?",
        options: ["Uko wapi?", "Bei gani?", "Nataka hii", "Asante sana"],
        optionTranslations: ["Where are you?", "How much / What is the price?", "I want this", "Thank you very much"],
        correctAnswerIndex: 1,
        pronunciation: "BEI GA-ni",
        explanation: "'Bei gani?' literally means 'What price?' and is essential in any market.",
        explanationTranslation: "'Bei gani?' literally means 'What price?' and is essential in any market.",
        audioPhrase: "Bei gani?",
      ),
      const Question(
        id: 106,
        questionType: "Shopping - Bargaining",
        questionTypeTranslation: "Ununuzi - Kupungua Bei",
        questionText: "How do you say 'Please reduce the price' in Swahili?",
        questionTranslation: "Unasemaje 'Punguza bei kidogo' kwa Kiswahili?",
        options: ["Naomba kupunguza bei", "Ninaenda soko", "Nimechoka", "Nipe zaidi"],
        optionTranslations: ["Please reduce the price", "I am going to the market", "I am tired", "Give me more"],
        correctAnswerIndex: 0,
        pronunciation: "Na-OM-ba ku-pun-GU-za BEI",
        explanation: "Bargaining is common at markets; 'Naomba kupunguza bei' politely asks for a discount.",
        explanationTranslation: "Bargaining is common at markets; 'Naomba kupunguza bei' politely asks for a discount.",
        audioPhrase: "Naomba kupunguza bei",
      ),
      const Question(
        id: 107,
        questionType: "Shopping - Numbers",
        questionTypeTranslation: "Ununuzi - Nambari",
        questionText: "What does 'elfu moja' mean?",
        questionTranslation: "Maana ya 'elfu moja' ni nini?",
        options: ["One hundred", "One thousand", "Ten", "One million"],
        optionTranslations: ["Mia moja", "Elfu moja", "Kumi", "Milioni moja"],
        correctAnswerIndex: 1,
        pronunciation: "EL-fu MO-ja",
        explanation: "'Elfu moja' means one thousand — useful for prices like '1,000 shillings'.",
        explanationTranslation: "'Elfu moja' means one thousand — useful for prices like '1,000 shillings'.",
        audioPhrase: "elfu moja",
      ),

      // --- Food & Eating Out ---
      const Question(
        id: 108,
        questionType: "Food - Ordering",
        questionTypeTranslation: "Chakula - Kuagiza",
        questionText: "How do you say 'I would like food, please'?",
        questionTranslation: "Unasemaje 'Naomba chakula' kwa Kiswahili?",
        options: ["Ninaenda nyumbani", "Naomba chakula", "Nimeshiba", "Ninataka maji"],
        optionTranslations: ["I am going home", "I would like food, please", "I am full", "I want water"],
        correctAnswerIndex: 1,
        pronunciation: "Na-OM-ba CHA-ku-la",
        explanation: "'Naomba chakula' politely requests food at a restaurant or home.",
        explanationTranslation: "'Naomba chakula' politely requests food at a restaurant or home.",
        audioPhrase: "Naomba chakula",
      ),
      const Question(
        id: 109,
        questionType: "Food - Drinks",
        questionTypeTranslation: "Chakula - Vinywaji",
        questionText: "How do you say 'I want tea' in Swahili?",
        questionTranslation: "Unasemaje 'Ninataka chai' kwa Kiswahili?",
        options: ["Ninataka kahawa", "Ninataka maji", "Ninataka chai", "Ninataka juisi"],
        optionTranslations: ["I want coffee", "I want water", "I want tea", "I want juice"],
        correctAnswerIndex: 2,
        pronunciation: "Ni-na-TA-ka CHAI",
        explanation: "Chai (tea with milk and spices) is the most popular drink in East Africa.",
        explanationTranslation: "Chai (tea with milk and spices) is the most popular drink in East Africa.",
        audioPhrase: "Ninataka chai",
      ),
      const Question(
        id: 110,
        questionType: "Food - Common Dish",
        questionTypeTranslation: "Chakula - Vyakula Maarufu",
        questionText: "What is 'ugali'?",
        questionTranslation: "Ugali ni nini?",
        options: ["A type of rice dish", "A stiff maize porridge", "A type of soup", "A grilled meat dish"],
        optionTranslations: ["Wali", "Ugali (uji mgumu wa mahindi)", "Mchuzi", "Nyama ya kuoka"],
        correctAnswerIndex: 1,
        pronunciation: "U-GA-li",
        explanation: "Ugali is a staple food made from maize flour, eaten with vegetables or meat.",
        explanationTranslation: "Ugali is a staple food made from maize flour, eaten with vegetables or meat.",
        audioPhrase: "ugali",
      ),

      // --- Transport & Directions ---
      const Question(
        id: 111,
        questionType: "Transport - Bus",
        questionTypeTranslation: "Usafiri - Basi",
        questionText: "What is a 'daladala'?",
        questionTranslation: "Daladala ni nini?",
        options: ["A type of food", "A minibus used for public transport", "A market stall", "A traditional dance"],
        optionTranslations: ["Aina ya chakula", "Minibasi ya usafiri wa umma", "Stendi ya soko", "Ngoma ya asili"],
        correctAnswerIndex: 1,
        pronunciation: "da-la-DA-la",
        explanation: "A daladala is a shared minibus taxi — the main form of public transport in Tanzania.",
        explanationTranslation: "A daladala is a shared minibus taxi — the main form of public transport in Tanzania.",
        audioPhrase: "daladala",
      ),
      const Question(
        id: 112,
        questionType: "Transport - Directions",
        questionTypeTranslation: "Usafiri - Mwelekeo",
        questionText: "How do you ask 'Where is the bus station?'",
        questionTranslation: "Unaulizaje 'Wapi kituo cha basi?'",
        options: ["Kituo cha basi kiko mbali", "Wapi kituo cha basi?", "Ninakwenda stendi", "Basi imechelewa"],
        optionTranslations: ["The bus station is far", "Where is the bus station?", "I am going to the station", "The bus is late"],
        correctAnswerIndex: 1,
        pronunciation: "WA-pi ki-TU-o cha BA-si",
        explanation: "Knowing how to ask for directions is essential when navigating a new city.",
        explanationTranslation: "Knowing how to ask for directions is essential when navigating a new city.",
        audioPhrase: "Wapi kituo cha basi?",
      ),
      const Question(
        id: 113,
        questionType: "Transport - Left & Right",
        questionTypeTranslation: "Usafiri - Kushoto na Kulia",
        questionText: "What does 'kushoto' mean?",
        questionTranslation: "Maana ya 'kushoto' ni nini?",
        options: ["Straight ahead", "Right", "Left", "Behind"],
        optionTranslations: ["Moja kwa moja", "Kulia", "Kushoto", "Nyuma"],
        correctAnswerIndex: 2,
        pronunciation: "ku-SHO-to",
        explanation: "'Kushoto' means left; 'kulia' means right — both essential for giving directions.",
        explanationTranslation: "'Kushoto' means left; 'kulia' means right — both essential for giving directions.",
        audioPhrase: "kushoto",
      ),

      // --- Family & Daily Routines ---
      const Question(
        id: 114,
        questionType: "Family - Members",
        questionTypeTranslation: "Familia - Wanafamilia",
        questionText: "What does 'familia' mean in Swahili?",
        questionTranslation: "Maana ya 'familia' ni nini kwa Kiswahili?",
        options: ["Friend", "Neighbour", "Family", "Colleague"],
        optionTranslations: ["Rafiki", "Jirani", "Familia", "Mwenzako"],
        correctAnswerIndex: 2,
        pronunciation: "fa-MI-lia",
        explanation: "'Familia' means family; an important word as family is central to Swahili culture.",
        explanationTranslation: "'Familia' means family; an important word as family is central to Swahili culture.",
        audioPhrase: "familia",
      ),
      const Question(
        id: 115,
        questionType: "Daily Routine - Morning",
        questionTypeTranslation: "Utaratibu - Asubuhi",
        questionText: "How do you say 'I wake up in the morning'?",
        questionTranslation: "Unasemaje 'Ninaamka asubuhi'?",
        options: ["Ninalala usiku", "Ninakula chakula", "Ninaamka asubuhi", "Ninaenda kazini"],
        optionTranslations: ["I sleep at night", "I eat food", "I wake up in the morning", "I go to work"],
        correctAnswerIndex: 2,
        pronunciation: "Ni-na-AM-ka a-su-BU-hi",
        explanation: "'Ninaamka asubuhi' — describing daily routines helps you connect with locals.",
        explanationTranslation: "'Ninaamka asubuhi' — describing daily routines helps you connect with locals.",
        audioPhrase: "Ninaamka asubuhi",
      ),
      const Question(
        id: 116,
        questionType: "Daily Routine - Days",
        questionTypeTranslation: "Utaratibu - Siku za Wiki",
        questionText: "What is 'Jumatatu' in English?",
        questionTranslation: "Jumatatu kwa Kiingereza ni nini?",
        options: ["Sunday", "Monday", "Friday", "Saturday"],
        optionTranslations: ["Jumapili", "Jumatatu", "Ijumaa", "Jumamosi"],
        correctAnswerIndex: 1,
        pronunciation: "Ju-ma-TA-tu",
        explanation: "'Jumatatu' is Monday — the week days in Swahili are based on Arabic numbering.",
        explanationTranslation: "'Jumatatu' is Monday — the week days in Swahili are based on Arabic numbering.",
        audioPhrase: "Jumatatu",
      ),

      // --- Health & Emergencies ---
      const Question(
        id: 117,
        questionType: "Health - Illness",
        questionTypeTranslation: "Afya - Ugonjwa",
        questionText: "How do you say 'I am sick / in pain'?",
        questionTranslation: "Unasemaje 'Ninaumwa'?",
        options: ["Ninahisi vizuri", "Ninaumwa", "Ninaenda hospitalini", "Ninahitaji dawa"],
        optionTranslations: ["I feel well", "I am sick / in pain", "I am going to the hospital", "I need medicine"],
        correctAnswerIndex: 1,
        pronunciation: "Ni-na-UM-wa",
        explanation: "'Ninaumwa' means 'I am in pain / sick' — crucial for seeking medical help.",
        explanationTranslation: "'Ninaumwa' means 'I am in pain / sick' — crucial for seeking medical help.",
        audioPhrase: "Ninaumwa",
      ),
      const Question(
        id: 118,
        questionType: "Health - Doctor",
        questionTypeTranslation: "Afya - Daktari",
        questionText: "How do you say 'I need a doctor'?",
        questionTranslation: "Unasemaje 'Nahitaji daktari'?",
        options: ["Nahitaji chakula", "Nahitaji daktari", "Nahitaji maji", "Nahitaji gari"],
        optionTranslations: ["I need food", "I need a doctor", "I need water", "I need a car"],
        correctAnswerIndex: 1,
        pronunciation: "Na-HI-ta-ji dak-TA-ri",
        explanation: "'Nahitaji daktari' — knowing this phrase could be lifesaving in an emergency.",
        explanationTranslation: "'Nahitaji daktari' — knowing this phrase could be lifesaving in an emergency.",
        audioPhrase: "Nahitaji daktari",
      ),
      const Question(
        id: 119,
        questionType: "Health - Emergency",
        questionTypeTranslation: "Afya - Dharura",
        questionText: "How do you shout 'Help!' in Swahili?",
        questionTranslation: "Unasemaje 'Msaada!' kwa Kiswahili?",
        options: ["Karibu!", "Polepole!", "Msaada!", "Subiri!"],
        optionTranslations: ["Welcome!", "Slowly!", "Help!", "Wait!"],
        correctAnswerIndex: 2,
        pronunciation: "Msa-A-da",
        explanation: "'Msaada!' means 'Help!' — essential to know in any emergency situation.",
        explanationTranslation: "'Msaada!' means 'Help!' — essential to know in any emergency situation.",
        audioPhrase: "Msaada!",
      ),
      const Question(
        id: 120,
        questionType: "Health - Pharmacy",
        questionTypeTranslation: "Afya - Duka la Dawa",
        questionText: "How do you say 'I need medicine' in Swahili?",
        questionTranslation: "Unasemaje 'Ninahitaji dawa'?",
        options: ["Ninahitaji chakula", "Ninahitaji dawa", "Ninahitaji pesa", "Ninahitaji ushauri"],
        optionTranslations: ["I need food", "I need medicine", "I need money", "I need advice"],
        correctAnswerIndex: 1,
        pronunciation: "Ni-na-hi-TA-ji DA-wa",
        explanation: "'Ninahitaji dawa' is what you say at a pharmacy ('duka la dawa').",
        explanationTranslation: "'Ninahitaji dawa' is what you say at a pharmacy ('duka la dawa').",
        audioPhrase: "Ninahitaji dawa",
      ),
      const Question(
        id: 121,
        questionType: "Greetings - Response",
        questionTypeTranslation: "Salamu - Jibu",
        questionText: "What is the reply to 'Habari yako?'",
        questionTranslation: "Unajibu nini kwa 'Habari yako?'",
        options: ["Kwa heri", "Nzuri / Salama", "Samahani", "Karibu"],
        optionTranslations: ["Goodbye", "Fine / I'm well", "Sorry", "Welcome"],
        correctAnswerIndex: 1,
        pronunciation: "N-ZU-ri / Sa-LA-ma",
        explanation: "'Nzuri' (fine/good) or 'Salama' (peaceful/well) are common replies to 'Habari yako?'",
        explanationTranslation: "'Nzuri' (fine/good) or 'Salama' (peaceful/well) are common replies to 'Habari yako?'",
        audioPhrase: "Nzuri, asante",
      ),
      const Question(
        id: 122,
        questionType: "Shopping - Payment",
        questionTypeTranslation: "Ununuzi - Malipo",
        questionText: "How do you say 'I will buy it' in Swahili?",
        questionTranslation: "Unasemaje 'Nitanunua' kwa Kiswahili?",
        options: ["Sitanunua", "Nitanunua", "Nimenunua", "Ninunue"],
        optionTranslations: ["I will not buy", "I will buy it", "I have bought", "Let me buy"],
        correctAnswerIndex: 1,
        pronunciation: "Ni-ta-NU-nu-a",
        explanation: "'Nitanunua' confirms your intention to buy — useful after successful bargaining.",
        explanationTranslation: "'Nitanunua' confirms your intention to buy — useful after successful bargaining.",
        audioPhrase: "Nitanunua",
      ),
    ];
  }
}
